sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: YsTeAjGWCWe9qeGGVCYEXDwIiQ8KPsrX40c1brWsjkR6Id4H/+UVzLriHFj3S63k4eDSnxQJIR7GxLalqYgaS0IgwNLXivInySrCKVsDBggBNPh4XWkJtlQiK7xFZNnXCxoxvafYHetJDhZIpILLRNemK2VGNvGwO7O4lx1OS8lhMnasGyRMrob5nd2qrL826yCa2Fw55U9xDXm/xyg/odaaDfYWiWS6/VJDi0Oogz7Z82AG8xKJh5enGcHV1a6DViww+PZx91q5sP7Bvy9Bkijn3pZDdq3voe1LZPG0LnQv10QRvehmgFps/nD3TPdqym1LAUXRQQMlnyLzdQAPTuRLw/c5QoYMOTqO/W+Ct0VSL5YFsY/o74lygcC+pGdrJ5Lx0JKgsxNlJK3P2P8g56ixRudft/83NPceb0DIaZdAYbv3PZ9O8f48DeXABSMQshwMRbmSgGiqTrQogb223ehJ0tQg6683ieYQC9D5kausXncd57i8I8BaC/pM/tjl+GDbCOeQMEQY2o3J4Bsc7p41nd0DqTOL8+UyRD/zjsllTvZebTFSls4//fN8v5v+pA1rydS5Iz/NmfV2WwhsPSuMRz6iO1KJQcuAxS/XwjtLiKHmCZYPYqLTsuLtEsdUuvzJsI3jn0RCgLp+zFhSkeiEx9ubfPCEnT1gxlc1Dq8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Tales-and-Novels-of-J-de-La-Fontaine-Volume-19_5293
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy